// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6pvSOEh2vQ7Ph-0zGcnC-jOQHvDgpfQE',
    appId: '1:725951205869:web:7aa1037230553d60f997e4',
    messagingSenderId: '725951205869',
    projectId: 'fitnesstrainerapp-d1251',
    authDomain: 'fitnesstrainerapp-d1251.firebaseapp.com',
    storageBucket: 'fitnesstrainerapp-d1251.appspot.com',
    measurementId: 'G-0TDGGQ91VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JJ_XE-t79k69QkTUCNTipiMG_0oRepA',
    appId: '1:725951205869:android:d22c70bacd8778f2f997e4',
    messagingSenderId: '725951205869',
    projectId: 'fitnesstrainerapp-d1251',
    storageBucket: 'fitnesstrainerapp-d1251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3aEPJY2sWEfCxMmyce-xqhIN2iusjZs',
    appId: '1:725951205869:ios:2439d04d3e0e36e5f997e4',
    messagingSenderId: '725951205869',
    projectId: 'fitnesstrainerapp-d1251',
    storageBucket: 'fitnesstrainerapp-d1251.appspot.com',
    iosBundleId: 'com.example.fitnessTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3aEPJY2sWEfCxMmyce-xqhIN2iusjZs',
    appId: '1:725951205869:ios:2439d04d3e0e36e5f997e4',
    messagingSenderId: '725951205869',
    projectId: 'fitnesstrainerapp-d1251',
    storageBucket: 'fitnesstrainerapp-d1251.appspot.com',
    iosBundleId: 'com.example.fitnessTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6pvSOEh2vQ7Ph-0zGcnC-jOQHvDgpfQE',
    appId: '1:725951205869:web:dc3ce68091ea052ef997e4',
    messagingSenderId: '725951205869',
    projectId: 'fitnesstrainerapp-d1251',
    authDomain: 'fitnesstrainerapp-d1251.firebaseapp.com',
    storageBucket: 'fitnesstrainerapp-d1251.appspot.com',
    measurementId: 'G-P03BQK7L4V',
  );
}
